### PR TITLE
Code generalisation for multiple votes to be added

### PR DESCRIPTION
**Pull request by Luker501**
The main contribution of my pull request is the maci/ZK_Snarks/Add_Multiple_Leaves/ folder where I have generalised the code so that multiple votes can be added at the same time. This example is working now due to the help of theRealYingTong and kobigurk.

I also added the circomlib folder which is required for our both circom examples (add a single vote and add multiple votes) to work correctly. Note that I don't think we are using all of the circomlib folder, so later we can prune what is in it.

### CODE REVIEW

**Comment by barryWhiteHat** [comment]
Can you add circomlib as a sub module like we do https://github.com/rollupnc/RollupNC

**Comment by Luker501** [comment]
I've deleted all the json files. I tried to minimise the circomlib folder but then I started to introduce errors, so I have left it alone for now.

**Comment by barryWhiteHat** [comment]
Hi Sorry i only saw this comment now. I have made a PR into your repo that removes circom lib and replaces it with a submodle https://github.com/Luker501/maci/pull/1

If you accept this it iwll atomatically be applied to this pull request and i can merge it then. But make sure the tests are passing once it is updated.

**Comment by weijiekoh** [comment]
Shall we close this PR?

**Comment by barryWhiteHat** [comment]
Sure as this feature has been added already :)

**Pull request closed without merging**
