### PR TITLE
Use Poseidon hash function

### PR DESCRIPTION
**Pull request by ChihChengLiang**
This is an attempt to address #63

TODO:

- [x] Try profiling existing mimcsponge hashers
  - [x] hasherN
  - [x] hashLeftRight
- [x] Implement Poseidon circuit.
- [x] Try different `t` for Poseidon.
- [ ] Try different merklizing strategy
  - [ ] naive: t=6 for 5 element object, and then merklize with t=3 left-right hasher
  - [ ] merklize with same sponge hash: t=6 for 5 element object, then build merkle tree with the same hash that takes 5 input nodes.

- Benchmarks
  - [x] Circuit constraints
  - [x] use `calculateWitness` time as a metric for time (proving time is the correct metric?)
  - [ ] Profiling gas cost

```
=========MIMC=============
Hasher 5
circuit.nConstraints 3300
Benchmark took 50020203 nanoseconds
--------------------------
Hasher 10
circuit.nConstraints 6600
Benchmark took 69417551 nanoseconds
--------------------------
HashLeftRight
circuit.nConstraints 1320
Benchmark took 13969494 nanoseconds
--------------------------
```

```
=========Poseidon=========
Hasher 5
circuit.nConstraints 312
Benchmark took 31712905 nanoseconds
--------------------------
Hasher 10
circuit.nConstraints 432
Benchmark took 63015542 nanoseconds
--------------------------
HashLeftRight
circuit.nConstraints 240
Benchmark took 9308105 nanoseconds
--------------------------

```

### CODE REVIEW

**Comment by weijiekoh** [comment]
Thank you! I got similar performance results.

It seems that with MiMCSponge, the number of constraints grows linearly.

It would be great to figure out if the same could be said about a PoseidonSponge circuit.

If we could implement this circuit, and if that uses fewer constraints than, for instance, Poseidon5 or Poseidon10 with custom `t` values, then we should seriously consider using it.

What do you think?

Copying in @kobigurk for your views :)

Thank you!

**Comment by ChihChengLiang** [comment]
Yeah, definitely worth exploring Poseidon. I'm still working on the Poseidon circuits 😅, hope it will perform better.

**Comment by ChihChengLiang** [comment]
Updated Poseidon benchmarks
This is using t=6 for nInput=5 and t=11 for nInput=10. Using all with `Rf=8` and `Rp=57`.

```
=========Poseidon=========
Hasher 5
circuit.nConstraints 312
Benchmark took 31712905 nanoseconds
--------------------------
Hasher 10
circuit.nConstraints 432
Benchmark took 63015542 nanoseconds
--------------------------
HashLeftRight
circuit.nConstraints 240
Benchmark took 9308105 nanoseconds
--------------------------
```

**Comment by ChihChengLiang** [comment]
Gain from adjusting Rf and Rp is minor but let's still report here.

```
=========Poseidon=========
Hasher 5
circuit.nConstraints 291
Benchmark took 29427262 nanoseconds
--------------------------
Hasher 10
circuit.nConstraints 414
Benchmark took 60565124 nanoseconds
--------------------------
HashLeftRight
circuit.nConstraints 216
Benchmark took 10616823 nanoseconds
```

**Comment by ChihChengLiang** [comment]
Moving on exploring the Merkle tree mode.

**Comment by ChihChengLiang** [comment]
Close for outdated

**Pull request closed without merging**
